### ISSUE TITLE
Graphs

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/presentations#1]
Should we put some graphs in here as well? E.g. growth over time etc.? So they are easily available for new slides etc?

**Comment by philippbayer** [comment]
R scripts are in the opensnp_misc folder as starting points :)

These are the ones I've made in the past and we used in posters/presentations (phenotypes, user_phenotypes growth, user growth, genotypes growth)

**Comment by gedankenstuecke** [comment]
Ok, will do some graphs based on this, extend the code etc.
